- name: Deploy to Tomcat
  hosts: web
  become: yes

  tasks:

    - name: Copy WAR file to Tomcat
      copy:
        src: "../target/ansapp.war"
        dest: "/opt/tomcat/webapps/ansapp.war"
        remote_src: no

    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
